# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/barreto/bin/cmake-3.10.2-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/barreto/bin/cmake-3.10.2-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/barreto/github/DyNaMol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/barreto/github/DyNaMol

# Utility rule file for UserManual_safepdf.

# Include the progress variables for this target.
include CMakeFiles/UserManual_safepdf.dir/progress.make

CMakeFiles/UserManual_safepdf:
	/home/barreto/bin/cmake-3.10.2-Linux-x86_64/bin/cmake -E chdir /home/barreto/github/DyNaMol/doc /usr/bin/ps2pdf14 -dMaxSubsetPct=100 -dCompatibilityLevel=1.3 -dSubsetFonts=true -dEmbedAllFonts=true -dAutoFilterColorImages=false -dAutoFilterGrayImages=false -dColorImageFilter=/FlateEncode -dGrayImageFilter=/FlateEncode -dMonoImageFilter=/FlateEncode UserManual.ps UserManual.pdf

UserManual_safepdf: CMakeFiles/UserManual_safepdf
UserManual_safepdf: CMakeFiles/UserManual_safepdf.dir/build.make

.PHONY : UserManual_safepdf

# Rule to build all files generated by this target.
CMakeFiles/UserManual_safepdf.dir/build: UserManual_safepdf

.PHONY : CMakeFiles/UserManual_safepdf.dir/build

CMakeFiles/UserManual_safepdf.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/UserManual_safepdf.dir/cmake_clean.cmake
.PHONY : CMakeFiles/UserManual_safepdf.dir/clean

CMakeFiles/UserManual_safepdf.dir/depend:
	cd /home/barreto/github/DyNaMol && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/barreto/github/DyNaMol /home/barreto/github/DyNaMol /home/barreto/github/DyNaMol /home/barreto/github/DyNaMol /home/barreto/github/DyNaMol/CMakeFiles/UserManual_safepdf.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/UserManual_safepdf.dir/depend

